CREATE SEQUENCE SEQ_USUARIOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_USUARIOS (
    ID INTEGER DEFAULT SEQ_USUARIOS.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_CADASTRO DATE NOT NULL
);