CREATE SEQUENCE SEQ_EQUIPAMENTOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_EQUIPAMENTOS (
    ID INTEGER DEFAULT SEQ_EQUIPAMENTOS.NEXTVAL NOT NULL,
    TIPO_EQUIPAMENTO VARCHAR2(100) NOT NULL,
    CONSUMO_ENERGIA VARCHAR2(50) NOT NULL,
    LOCALIZACAO VARCHAR2(100) NOT NULL,
    SENSOR_ID VARCHAR2(8) NOT NULL,
    DATA_CONSUMO DATE NOT NULL
);