name: CI/CD - Energia (Docker, uma branch)

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

env:
  WORKDIR: energia/energia
  JAVA_VERSION: '21'
  DEPLOY_BRANCH: 'master'
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/energia

jobs:
  build-and-test:
    name: Build & Test (Maven)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Run unit tests
        working-directory: ${{ env.WORKDIR }}
        run: mvn -B -ntp test

      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: ${{ env.WORKDIR }}/target/surefire-reports/*
          if-no-files-found: ignore

  dockerize-and-push:
    name: Build & Push Docker
    needs: build-and-test
    if: ${{ github.event_name == 'push' && github.ref_name == env.DEPLOY_BRANCH }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=raw,value=${{ env.DEPLOY_BRANCH }}-staging      # ex.: main-staging (staging)
            type=sha,prefix=sha-,format=long                     # ex.: sha-<commit> (produção)
            type=raw,value=latest                                # opcional

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKDIR }}
          file: ${{ env.WORKDIR }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-staging:
    needs: dockerize-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy container (staging)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_STAGING }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_STAGING }}
        images: ${{ env.DOCKER_IMAGE }}:${{ env.DEPLOY_BRANCH }}-staging

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
    - name: Deploy container (prod)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_PRODUCTION }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_PRODUCTION }}
        images: ${{ env.DOCKER_IMAGE }}:sha-${{ github.sha }}