name: CI/CD - pipeline

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "beta" ]

env:
  WORKDIR: energia
  JAVA_VERSION: '21'
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/energia

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-test:
    name: Build & Test (Maven)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Run unit tests
        working-directory: ${{ env.WORKDIR }}
        run: mvn -B -ntp test

      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: ${{ env.WORKDIR }}/target/surefire-reports/*
          if-no-files-found: ignore

      - name: Package (JAR)
        working-directory: ${{ env.WORKDIR }}
        run: mvn -B -ntp -DskipTests=false clean package

      - name: Upload build artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: energia-jar
          path: ${{ env.WORKDIR }}/target/*.jar
          if-no-files-found: error

  dockerize-and-push:
    name: Build & Push Docker
    needs: build-and-test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch,suffix=-staging   # ex.: refs-heads-main-staging (staging)
            type=sha,prefix=sha-,format=long         # ex.: sha-<commit> (produção)
            type=raw,value=latest                    # latest opcional

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKDIR }}
          file: ${{ env.WORKDIR }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-staging:
    name: Deploy Staging (Azure)
    needs: dockerize-and-push
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Deploy to Azure (staging)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_STAGING }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_STAGING }}
          images: ${{ env.DOCKER_IMAGE }}:refs-heads-main-staging

  deploy-production:
    name: Deploy Production (Azure)
    needs: deploy-staging
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy to Azure (production)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_PRODUCTION }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_PRODUCTION }}
          images: ${{ env.DOCKER_IMAGE }}:sha-${{ github.sha }}
